<!DOCTYPE html>
<html>
<head>
	<title>Promise API</title>
	<link rel="stylesheet" type="text/css" href="../../Assets/bulma.css">
	<link rel="stylesheet" type="text/css" href="../../Assets/Style.css">
	<script type="text/javascript" src="../../Assets/prism.min.js"></script>
	<script type="text/javascript" src="../../Assets/jquery.min.js"></script>
  <link rel="stylesheet" href="../../Assets/prism-dark.css">
</head>
<body class="Body">
<div class="Content Card">







<h1>Promise.resolve</h1>
<pre>
let promise = Promise.resolve(value);
</pre>
<p>Returns a resolved promise with the given value. Same as:</p>
<pre>
let promise = new Promise(resolve => resolve(value));
</pre>
<p>The method is used when we already have a value, but would like to have it “wrapped” into a promise.</p>
<p>For instance, the <code>loadCached</code> function below fetches the <code>url</code> and remembers the result, so that future calls on the same URL return it immediately:</p>
<pre>
function loadCached(url) {
  let cache = loadCached.cache || (loadCached.cache = new Map());

  if (cache.has(url)) {
    return Promise.resolve(cache.get(url)); // (*)
  }

  return fetch(url)
    .then(response => response.text())
    .then(text => {
      cache.set(url,text);
      return text;
    });
}
</pre>
<p>We can use <code>loadCached(url).then(…)</code>, because the function is guaranteed to return a promise. That’s the purpose <code>Promise.resolve</code> in the line <code>(*)</code>: it makes sure the interface unified. We can always use <code>.then</code> after <code>loadCached</code>.</p>








<h1>Promise.reject</h1>
<pre>
let promise = Promise.reject(error);
</pre>
<p>Create a rejected promise with the error.</p>
<pre>
let promise = new Promise((resolve, reject) => reject(error))
</pre>








<h1>Promise.all</h1>
<p>The method to run many promises in parallel and wait till all of them are ready.</p>
<pre>
let promise = Promise.all(iterable);
</pre>
<p>It takes an iterable object with promises, technically it can be any iterable, but usually it’s an array, and returns a new promise. The new promise resolves with when all of them are settled and has an array of their results.</p>
<p>For instance, the <code>Promise.all</code> below settles after 3 seconds, and then its result is an array <code>[1, 2, 3]</code>:</p>
<pre>
Promise.all([
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 3000)), // 1
  new Promise((resolve, reject) => setTimeout(() => resolve(2), 2000)), // 2
  new Promise((resolve, reject) => setTimeout(() => resolve(3), 1000))  // 3
]).then(alert); // 1,2,3 when promises are ready: each promise contributes an array member
</pre>
<p>Please note that the relative order is the same. Even though the first promise takes the longest time to resolve, it is still first in the array of results. A common trick is to map an array of job data into an array of promises, and then wrap that into <code>Promise.all</code>.</p>
<p>For instance, if we have an array of URLs, we can fetch them all like this:</p>
<pre>
let urls = [
  'https://api.github.com/users/iliakan',
  'https://api.github.com/users/remy',
  'https://api.github.com/users/jeresig'
];

// map every url to the promise fetch(github url)
let requests = urls.map(url => fetch(url));

// Promise.all waits until all jobs are resolved
Promise.all(requests)
  .then(responses => responses.forEach(
    response => alert(`${response.url}: ${response.status}`)
  ));
</pre>
<p>If any of the promises is rejected, Promise.all immediately rejects with that error.</p>
<pre>
Promise.all([
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error("Whoops!")), 2000)),
  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
]).catch(alert); // Error: Whoops!
</pre>
<p>Here the second promise rejects in two seconds. That leads to immediate rejection of <code>Promise.all</code>, so <code>.catch</code> executes: the rejection error becomes the outcome of the whole <code>Promise.all</code>.</p>
<p>The important detail is that promises provide no way to “cancel” or “abort” their execution. So other promises continue to execute, and the eventually settle, but all their results are ignored.</p>
<p>There are ways to avoid this: we can either write additional code to <code>clearTimeout</code> (or otherwise cancel) the promises in case of an error, or we can make errors show up as members in the resulting array (see the task below this chapter about it).</p>
<h3>Promise.all(iterable) allows non-promise items in iterable</h3>
<p>Normally, <code>Promise.all(iterable)</code> accepts an iterable (in most cases an array) of promises. But if any of those objects is not a promise, it’s wrapped in <code>Promise.resolve</code>.</p>
<p>For instance, here the results are <code>[1, 2, 3]</code>:</p>
<pre>
Promise.all([
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000)
  }),
  2, // treated as Promise.resolve(2)
  3  // treated as Promise.resolve(3)
]).then(alert); // 1, 2, 3
</pre>
<p>So we are able to pass non-promise values to <code>Promise.all</code> where convenient.</p>












<h1>Promise.race</h1>
<p>Similar to <code>Promise.all</code> takes an iterable of promises, but instead of waiting for all of them to finish – waits for the first result (or error), and goes on with it.</p>
<pre>
let promise = Promise.race(iterable);
</pre>
<p>For instance, here the result will be <code>1</code>:</p>
<pre>
Promise.race([
  new Promise((resolve, reject) => setTimeout(() => resolve(1), 1000)),
  new Promise((resolve, reject) => setTimeout(() => reject(new Error("Whoops!")), 2000)),
  new Promise((resolve, reject) => setTimeout(() => resolve(3), 3000))
]).then(alert); // 1
</pre>
<p>So, the first result/error becomes the result of the whole <code>Promise.race</code>. After the first settled promise “wins the race”, all further results/errors are ignored.</p>



























</div>
</body>
</html>